# Generated by Django 2.0.10 on 2019-01-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0002_auto_20190124_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='tax_service',
            field=models.CharField(choices=[('MANUAL', 'MANUAL'), ('CRYPTOTRADER', 'CRYPTOTRADER.TAX'), ('BITCOINTAX', 'BITCOIN.TAX'), ('COINTRACKER', 'COINTRACKER.IO')], max_length=100),
        ),
    ]
