# Generated by Django 2.0.10 on 2019-01-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0003_auto_20190124_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
