# Generated by Django 2.0.10 on 2019-01-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0004_auto_20190125_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='date',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
