# Generated by Django 2.0.10 on 2019-01-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0005_auto_20190125_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
