# Generated by Django 2.0.10 on 2019-01-25 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0007_auto_20190125_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversion',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='conversion',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
