# Generated by Django 2.0.10 on 2019-01-28 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0008_auto_20190125_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='file_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
