# Generated by Django 2.0.10 on 2019-01-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0009_conversion_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
