# Generated by Django 2.0.10 on 2019-01-31 02:47

import config.settings.local
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0009_conversion_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='file',
            field=models.FileField(blank=True, storage=config.settings.local.MediaRootS3Boto3Storage(), upload_to=''),
        ),
    ]
