# Generated by Django 2.0.10 on 2019-01-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0010_conversion_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversion',
            name='file',
        ),
        migrations.AddField(
            model_name='conversion',
            name='file_url',
            field=models.URLField(blank=True),
        ),
    ]
