# Generated by Django 2.0.10 on 2019-01-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0011_auto_20190131_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='file_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
