# Generated by Django 2.0.10 on 2019-01-27 07:01

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_newspage_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('body', wagtail.core.blocks.RawHTMLBlock(classname='body'))]),
        ),
    ]
