# Generated by Django 2.0.10 on 2019-01-27 22:59

from django.db import migrations
import django.utils.timezone
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_remove_homepage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='title_text',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
