# Generated by Django 2.0.10 on 2019-01-27 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20190127_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='title_text',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
