# Generated by Django 2.0.10 on 2019-01-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coreindexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='revised_date',
            field=models.DateField(blank=True, verbose_name='revised date'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='date',
            field=models.DateField(blank=True, verbose_name='Post date'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='revised_date',
            field=models.DateField(blank=True, verbose_name='revised date'),
        ),
    ]
