# Generated by Django 2.0.10 on 2019-01-27 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('core', '0003_auto_20190127_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='Your Facebook page URL', null=True)),
                ('instagram', models.URLField(blank=True, help_text='Your Instagram URL', max_length=255, null=True)),
                ('twitter', models.URLField(blank=True, help_text='Your Twitter URL', max_length=255, null=True)),
                ('youtube', models.URLField(blank=True, help_text='Your YouTube Channel URL', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='Your Linkedin URL', max_length=255, null=True)),
                ('github', models.URLField(blank=True, help_text='Your Github URL', max_length=255, null=True)),
                ('facebook_appid', models.CharField(blank=True, help_text='Your Facbook AppID', max_length=255, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
