# Generated by Django 2.0.10 on 2019-01-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_socialmediasettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='date',
            field=models.DateField(verbose_name='Post date'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='revised_date',
            field=models.DateField(blank=True, verbose_name='revised date'),
        ),
    ]
