# Generated by Django 2.0.10 on 2019-01-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_externalfooterlinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalfooterlinks',
            name='name',
        ),
    ]
