# Generated by Django 2.0.10 on 2019-01-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_externalfooterlinks_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalfooterlinks',
            name='link_four',
            field=models.URLField(blank=True, help_text='Third URL', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='externalfooterlinks',
            name='link_one',
            field=models.URLField(blank=True, help_text='First URL', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='externalfooterlinks',
            name='link_three',
            field=models.URLField(blank=True, help_text='Third URL', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='externalfooterlinks',
            name='link_two',
            field=models.URLField(blank=True, help_text='Second URL', max_length=255, null=True),
        ),
    ]
