# Generated by Django 2.0.10 on 2019-01-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190128_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_name', models.CharField(help_text='Name of the link', max_length=200)),
                ('link_url', models.URLField(max_length=255)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='externalfooterlinks',
            name='link_four',
        ),
        migrations.RemoveField(
            model_name='externalfooterlinks',
            name='link_one',
        ),
        migrations.RemoveField(
            model_name='externalfooterlinks',
            name='link_three',
        ),
        migrations.RemoveField(
            model_name='externalfooterlinks',
            name='link_two',
        ),
    ]
