# Generated by Django 2.0.10 on 2019-01-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190128_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externallinks',
            options={},
        ),
        migrations.RemoveField(
            model_name='externallinks',
            name='sort_order',
        ),
    ]
