# Generated by Django 2.0.10 on 2019-01-28 19:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190128_1931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalLinks',
        ),
        migrations.AddField(
            model_name='externalfooterlinks',
            name='link_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externalfooterlinks',
            name='link_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
