# Generated by Django 2.0.10 on 2019-01-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190128_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalfooterlinks',
            name='link_four_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='externalfooterlinks',
            name='link_four_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='externalfooterlinks',
            name='link_one_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='externalfooterlinks',
            name='link_one_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='externalfooterlinks',
            name='link_three_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='externalfooterlinks',
            name='link_three_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='externalfooterlinks',
            name='link_two_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='externalfooterlinks',
            name='link_two_url',
            field=models.URLField(blank=True),
        ),
    ]
