# Generated by Django 2.0.10 on 2019-01-28 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190128_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalfooterlinks',
            name='link_four_name',
        ),
        migrations.RemoveField(
            model_name='externalfooterlinks',
            name='link_four_url',
        ),
        migrations.RemoveField(
            model_name='externalfooterlinks',
            name='link_one_name',
        ),
        migrations.RemoveField(
            model_name='externalfooterlinks',
            name='link_one_url',
        ),
        migrations.RemoveField(
            model_name='externalfooterlinks',
            name='link_three_name',
        ),
        migrations.RemoveField(
            model_name='externalfooterlinks',
            name='link_three_url',
        ),
        migrations.RemoveField(
            model_name='externalfooterlinks',
            name='link_two_name',
        ),
        migrations.RemoveField(
            model_name='externalfooterlinks',
            name='link_two_url',
        ),
        migrations.RemoveField(
            model_name='externalfooterlinks',
            name='site',
        ),
        migrations.AddField(
            model_name='externalfooterlinks',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externalfooterlinks',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
